# Generated by Django 2.2.7 on 2019-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('filename', models.TextField()),
                ('content', models.TextField()),
                ('and_attr', models.IntegerField()),
                ('or_attr', models.IntegerField()),
            ],
        ),
    ]
